apiVersion: apps/v1
kind: Deployment
metadata:
  name: Reactjs
  namespace: default
  labels:
    app: MYReactjsAPP
spec:
  selector:
    matchLabels:
      app: Reactjs
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Reactjs
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
      - name: Reactjs
        image: ravioneconnect/reactjs:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi

      restartPolicy: Always
